learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
'''Defining URL schemes for learning_logs'''
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
	#Home page
	path('', views.index, name='index'),
	#Page with List of all themes
	path('topics/', views.topics, name='topics'),
	#Page with information about choosing theme
	path('topics/<int:topic_id>/', views.topic, name='topic'),
	#Page for adding new theme
	path('new_topic/', views.new_topic, name='new_topic'),
	#Page for adding new enrty
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	#Page for editing entries
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
	#Turn on URL authorisation by default
	path('', include('django.contrib.auth.urls')),
	#Registration page
	path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	'''Theme which user learns'''
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

class Entry(models.Model):
	'''Info that user lernt inthe theme'''
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)


	class Meta:
		verbose_name_plural = 'entries'

		def __str__(self):
			'''Return str view of model'''
			if len(self.text) > 50:
				return f"{self.text[:50]}..."
			else:
				return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
	'''Home page of the Learning Log app'''
	return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
	'''List of themes'''
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics' : topics}
	return render(request, 'learning_logs/topics.html', context)

# def check_topic_owner(owner):
# 	'''Checking that topic has owned by current user'''
# 	if topic.owner != request.user:
# 		raise Http404

@login_required
def topic(request, topic_id):
	'''List of notes in one themes'''
	topic = get_object_or_404(Topic,id=topic_id)
	if topic.owner != request.user:
		 raise Http404
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic' : topic, 'entries' : entries}
	return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
	'''Define new theme'''
	if request.method != 'POST':
		#Creating black form
		form = TopicForm()
	else:
		#POST data was sent, utilize data
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs:topics')
	#Show blank form
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	'''adding new entry in  theme'''
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		#data wasn't send, creating blank form
		form = EntryForm()
	else:
		#POST data was sent, utilize data
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			if topic.owner != request.user:
				raise Http404
			new_entry.save()
			return redirect('learning_logs:topic', topic_id=topic_id)
	#Show blank form
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''Editing entry'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
    	raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # POST data sending
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('learning_logs:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,
     shrink-to-fit=no">
   <title>Learning Log</title>

   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}

  </head>
  <body>
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
  		<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
      		Learning Log</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse"
      		data-target="#navbarCollapse" aria-controls="navbarCollapse"
      		aria-expanded="false" aria-label="Toggle navigation">
    	  <span class="navbar-toggler-icon"></span></button>
    	<div class="collapse navbar-collapse" id="navbarCollapse">
  		  <ul class="navbar-nav mr-auto">
    		<li class="nav-item">
      		  <a class="nav-link" href="{% url 'learning_logs:topics' %}">
          			Topics</a></li>
  		  </ul>
  		  <ul class="navbar-nav ml-auto">
  		  	{% if user.is_authenticated %}
  		  	  <li class="nav-item">
  		  	  	<span class="navbar-text">Hello, {{ user.username }}.</span>
			  </li>
			  <li class="nav-item">
			  	<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          	  </li>
        	{% else %}
          	  <li class="nav-item">
            	<a class="nav-link" href="{% url 'users:register' %}">Register</a>
          	  </li>
          	  <li class="nav-item">
            	<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        	{% endif %}
		  </ul>
		</div>
	</nav>

	<main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
	  <div>
		{% block content %}{% endblock content %}
      </div>
    </main>

  </body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %} 
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}

	<!--p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p-->
	  <p>Edit entry:</p>
	  <form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
	    {% csrf_token %}
	    {% bootstrap_form form %}
	   	{% buttons %}
      		<button name="submit" class="btn btn-primary">save changes</button>
    	{% endbuttons %}
	  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class='jumbotron'>
    <h1 class="display-3">Track your learning.</h1>
    
    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
  </div>

{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %} 
  <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
{% endblock page_header %}

{% block content %}
	<p>New entry:</p>
	<form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class='form'>
	    {% csrf_token %}
	    {% bootstrap_form form %}
	    {% buttons %}
      		<button name="submit" class="btn btn-primary">add entry</button>
    	{% endbuttons %}
	</form>
	  
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3>Add a new topic:</h3>
{% endblock page_header %}

{% block content %}

	<form method="post" action="{% url 'learning_logs:new_topic' %}" class='form'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
      		<button name="submit" class="btn btn-primary">add topic</button>
    	{% endbuttons %}

	</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h3><a href="{% url 'learning_logs:topics' %}">Topic:</a> {{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %} 
  <h2>Topics</h2>
{% endblock page_header %}

{% block content %}
	  <ul>
	    {% for topic in topics %}
	      <li><h3>
	      	<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	      </h3></li>
	    {% empty %}
	      <li><h4>No topics have been added yet</h4></li>
	    {% endfor %}
	  </ul>

	  <p><a href="{% url 'learning_logs:new_topic' %}">Add new topic</a></p>
	  
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %} 
  <h3><a href="{% url 'learning_logs:index' %}">Registration</a></h3>
{% endblock page_header %}

{% block content %}
 
  <form method="post" action="{% url 'users:register' %}" class='form'>
    {% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
      	<button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
  
{% endblock content %}